services:
  postgres:
    image: postgres:16
    container_name: mercadolocal-postgres-micro-root
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pERSONAL04
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend-micro/sql/crear_bd.sql:/docker-entrypoint-initdb.d/01-crear_bd.sql:ro

volumes:
  postgres_data:
