services:
  postgres-micro:
    image: postgres:16
    container_name: mercadolocal-postgres-micro
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pERSONAL04
    ports:
      - '5433:5432'
    volumes:
      - postgres_micro_data:/var/lib/postgresql/data
      - ./sql/crear_bd.sql:/docker-entrypoint-initdb.d/01-crear_bd.sql:ro

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mercadolocal-rabbitmq
    restart: unless-stopped
    ports:
      - '5673:5672'
      - '15673:15672'

  clientes-service:
    build: ./clientes-service
    container_name: mercadolocal-clientes-service
    restart: unless-stopped
    environment:
      POSTGRES_HOST: postgres-micro
      POSTGRES_PORT: 5432
      POSTGRES_DB: bd_clientes_ms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pERSONAL04
      ENABLE_RABBIT: 'false'
    depends_on:
      - postgres-micro
    ports:
      - '8001:8001'

  pedidos-service:
    build: ./pedidos-service
    container_name: mercadolocal-pedidos-service
    restart: unless-stopped
    environment:
      POSTGRES_HOST: postgres-micro
      POSTGRES_PORT: 5432
      POSTGRES_DB: bd_pedidos_ms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pERSONAL04
      CLIENTES_SERVICE_URL: http://clientes-service:8001
      ENABLE_RABBIT: 'false'
    depends_on:
      - postgres-micro
      - clientes-service
    ports:
      - '8002:8002'

  repartidores-service:
    build: ./repartidores-service
    container_name: mercadolocal-repartidores-service
    restart: unless-stopped
    environment:
      POSTGRES_HOST: postgres-micro
      POSTGRES_PORT: 5432
      POSTGRES_DB: bd_repartidores_ms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pERSONAL04
    depends_on:
      - postgres-micro
    ports:
      - '8003:8003'

  vendedores-service:
    build: ./vendedores-service
    container_name: mercadolocal-vendedores-service
    restart: unless-stopped
    environment:
      POSTGRES_HOST: postgres-micro
      POSTGRES_PORT: 5432
      POSTGRES_DB: bd_vendedores_ms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pERSONAL04
    depends_on:
      - postgres-micro
    ports:
      - '8004:8004'

  productos-service:
    build: ./productos-service
    container_name: mercadolocal-productos-service
    restart: unless-stopped
    environment:
      POSTGRES_HOST: postgres-micro
      POSTGRES_PORT: 5432
      POSTGRES_DB: bd_productos_ms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pERSONAL04
    depends_on:
      - postgres-micro
    ports:
      - '8005:8005'

volumes:
  postgres_micro_data:
